//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationRouteInfo", Namespace="http://schemas.datacontract.org/2004/07/LiveJourneys.JourneyPlanningSystem.WebSer" +
        "vice.Model")]
    [System.SerializableAttribute()]
    public partial class StationRouteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JourneyPlanningSystemService.IJourneyPlanningSystem")]
    public interface IJourneyPlanningSystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJourneyPlanningSystem/DoWork", ReplyAction="http://tempuri.org/IJourneyPlanningSystem/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJourneyPlanningSystem/DoWork", ReplyAction="http://tempuri.org/IJourneyPlanningSystem/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJourneyPlanningSystem/GetRouteInformation", ReplyAction="http://tempuri.org/IJourneyPlanningSystem/GetRouteInformationResponse")]
        LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.StationRouteInfo GetRouteInformation(int fromStationId, int toStationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJourneyPlanningSystem/GetRouteInformation", ReplyAction="http://tempuri.org/IJourneyPlanningSystem/GetRouteInformationResponse")]
        System.Threading.Tasks.Task<LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.StationRouteInfo> GetRouteInformationAsync(int fromStationId, int toStationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJourneyPlanningSystemChannel : LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.IJourneyPlanningSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JourneyPlanningSystemClient : System.ServiceModel.ClientBase<LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.IJourneyPlanningSystem>, LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.IJourneyPlanningSystem {
        
        public JourneyPlanningSystemClient() {
        }
        
        public JourneyPlanningSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JourneyPlanningSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JourneyPlanningSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JourneyPlanningSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.StationRouteInfo GetRouteInformation(int fromStationId, int toStationId) {
            return base.Channel.GetRouteInformation(fromStationId, toStationId);
        }
        
        public System.Threading.Tasks.Task<LiveJourneys.JourneyPlanningSystem.Web.JourneyPlanningSystemService.StationRouteInfo> GetRouteInformationAsync(int fromStationId, int toStationId) {
            return base.Channel.GetRouteInformationAsync(fromStationId, toStationId);
        }
    }
}
